# ansible/roles/system_hardening/tasks/main.yml
---
- name: Install security packages
  apt:
    name:
      - ufw
      - fail2ban
      - unattended-upgrades
      - logrotate
      - rsyslog
    state: present

- name: Configure automatic security updates
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Configure UFW firewall
  block:
    - name: Reset UFW to defaults
      ufw:
        state: reset

    - name: Configure UFW defaults
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      with_items:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Allow SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Allow Prometheus
      ufw:
        rule: allow
        port: '9090'
        proto: tcp

    - name: Allow Grafana
      ufw:
        rule: allow
        port: '3000'
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        logging: 'on'

- name: Configure fail2ban for SSH
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: Set up log rotation for monitoring logs
  template:
    src: monitoring-logs.j2
    dest: /etc/logrotate.d/monitoring-logs
    mode: '0644'

- name: Configure system limits
  template:
    src: 99-monitoring.conf.j2
    dest: /etc/security/limits.d/99-monitoring.conf
    mode: '0644'

- name: Configure sysctl parameters for monitoring
  template:
    src: 99-monitoring-sysctl.conf.j2
    dest: /etc/sysctl.d/99-monitoring-sysctl.conf
    mode: '0644'
  notify: reload sysctl

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Configure NTP
  apt:
    name: chrony
    state: present

- name: Start and enable chrony
  systemd:
    name: chrony
    state: started
    enabled: yes

- name: Create monitoring directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  with_items:
    - "{{ monitoring_dir }}"
    - "{{ prometheus_data_dir }}"
    - "{{ grafana_data_dir }}"
    - "{{ monitoring_dir }}/configs"
